language: python
env:
  - ANSIBLE_VERSION="2.4.*" # First released on 2017-09-19
  - ANSIBLE_VERSION="2.3.*" # First released on 2017-04-12
  - ANSIBLE_VERSION="2.2.*" # First released on 2016-11-01
  - ANSIBLE_VERSION="2.1.*" # First released on 2016-05-25
  - ANSIBLE_VERSION="2.0.*" # First released on 2016-01-12
  - ANSIBLE_VERSION="1.9.*" # First released on 2015-03-26
before_install:
  - sudo apt-get update -qq
install:
  - pip install ansible==$ANSIBLE_VERSION
script:
  # Check the role syntax
  - ansible-playbook --inventory='localhost,' tests/test.yml --syntax-check
  # Check that the role can run with no errors/failures
  - ansible-playbook --inventory='localhost,' tests/test.yml --connection=local -vvvv
  # Check idempotence of the role by running it twice and making sure there are
  # no changed/failed tasks
  - >
    ansible-playbook --inventory='localhost,' tests/test.yml --connection=local
    | tee /dev/stderr
    | grep -q 'changed=0.*failed=0'
    && (printf '\n*** Idempotence test: ok ***\n' && exit 0)
    || (printf "\n*** Idempotence test: failed ***\n" && exit 1)
  - ./tests/tests.sh
sudo: required
